<?php

    $sub="c";
    $pag="6";

?>

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    
    <!-- ---Font Awesome CDN-- -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">  

    <title>Compilation in C</title>


    <link rel="stylesheet" href="stylesheet/style.css">



</head>

<body>
    <!-- -----------------Header Module--------------- -->
    <?php

    include 'modules/_header_module.php';

    ?>



    <!-- ----------C Introduction section------------ -->
    <div class="container">
        <h1>Compilation process in C</h1>
        <div>
            <a href="c-5.php" class="btn btn-outline-primary"><i class="fa fa-arrow-left" aria-hidden="true"></i>  Previous</a>
            <a href="c-7.php" class="btn btn-outline-primary">Next  <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
        </div>


        <hr>
        <h3>What is a compilation?</h3>
        <p>The compilation is a process of converting the source code into object code. <br>
           It is done with the help of the compiler. <br>
           The compiler checks the source code for the syntactical or structural errors, and if the source code is error-free, then it generates the object code.<br>
           The c compilation process converts the source code taken as input into the object code or machine code. The compilation process can be divided into four steps, i.e., Pre-processing, Compiling, Assembling, and Linking.<br>
           The preprocessor takes the source code as an input, and it removes all the comments from the source code. The preprocessor takes the preprocessor directive and interprets it. <br>
           For example, if <stdio.h>, the directive is available in the program, then the preprocessor interprets the directive and replace this directive with the content of the 'stdio.h'file. <br>
        </p>
           Preprocessor
           The source code is the code which is written in a text editor and the source code file is given an extension ".c". <br>
           This source code is first passed to the preprocessor, and then the preprocessor expands this code. After expanding the code, the expanded code is passed to the compiler.<br>
           

        </p>
        <p><li>Compiler</li>
            The code which is expanded by the preprocessor is passed to the compiler.<br>
            The compiler converts this code into assembly code. Or we can say that the C compiler converts the pre-processed code into assembly code.
        </p>
       <p><li>Assembler</li>
           The assembly code is converted into object code by using an assembler.<br>
           The name of the object file generated by the assembler is the same as the source file. <br>
           The extension of the object file in DOS is '.obj,' and in UNIX, the extension is 'o'. <br>
           If the name of the source file is 'hello.c', then the name of the object file would be 'hello.obj'.
        </p>
        <p> <li>Linker </li>
           Mainly, all the programs written in C use library functions. <br>
           These library functions are pre-compiled, and the object code of these library files is stored with '.lib' (or '.a') extension. <br> 
           The main working of the linker is to combine the object code of library files with the object code of our program.<br>
           Sometimes the situation arises when our program refers to the functions defined in other files; then linker plays a very important role in this. <br>
           It links the object code of these files to our program. <br> 
        </p>

       <hr>
        <div class="mb-2">
            <a href="c-5.php" class="btn btn-outline-primary"><i class="fa fa-arrow-left" aria-hidden="true"></i>  Previous</a>
            <a href="c-7.php" class="btn btn-outline-primary">Next  <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
        </div>

        <hr>
        <div class="mb-2">
            <?php

            include 'modules/_query_module.php';

            ?>
        </div>


    </div>




    <!-- ------Footer Module----- -->
    <?php

    include 'modules/_footer_module.php';

    ?>




    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>

</html>